# Generated by Django 5.0.1 on 2024-08-31 17:53

import user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_parent_username_parent_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='parent',
            managers=[
                ('objects', user.models.ParentManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='parent',
            name='email',
        ),
    ]
