# Generated by Django 5.0.1 on 2024-08-31 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_parent_managers_remove_parent_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='parent',
            managers=[
            ],
        ),
    ]
