# Generated by Django 5.0.1 on 2024-08-31 17:57

import user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_parent_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='parent',
            managers=[
                ('objects', user.models.ParentManager()),
            ],
        ),
    ]
