# Generated by Django 5.1 on 2024-09-18 10:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_fee_missedevent_notification_teacher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missedevent',
            old_name='discription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='missedevent',
            name='picture',
            field=models.ImageField(null=True, upload_to='users/images'),
        ),
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(null=True, upload_to='user/images'),
        ),
        migrations.AddField(
            model_name='school',
            name='school_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='user/images'),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='user.teacher'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='status',
            field=models.CharField(choices=[('Paid', 'PAID'), ('Unpaid', 'UNPAID')], max_length=7),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid Ethiopian phone number starting with 251 or 09 and followed by 8 digits.', regex='^2519\\d{8}$|^09\\d{8}$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_ID',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
