# Generated by Django 5.1 on 2024-09-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_teacher_profile_pic_alter_fee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='types',
            field=models.CharField(choices=[('Tuition', 'Tuition'), ('Lunch', 'Lunch'), ('Transport', 'Transport'), ('Uniform', 'Uniform'), ('Book', 'Book'), ('Other', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='status',
            field=models.CharField(choices=[('Paid', 'PAID'), ('UNPAID', 'Unpaid')], max_length=7),
        ),
    ]
