# Generated by Django 5.1 on 2024-09-20 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_fee_types_alter_fee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fee',
            name='status',
            field=models.CharField(choices=[('Paid', 'PAID'), ('Unpaid', 'UNPAID')], max_length=7),
        ),
    ]
