# Generated by Django 5.1 on 2024-09-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_event_date_event_title_alter_fee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserecommendation',
            name='poster',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='fee',
            name='status',
            field=models.CharField(choices=[('Paid', 'PAID'), ('Unpaid', 'UNPAID')], max_length=7),
        ),
    ]
