# Generated by Django 5.1 on 2024-09-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_courserecommendation_poster_alter_fee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionrequest',
            name='reason',
            field=models.TextField(null=True),
        ),
    ]
